DROP TABLE IF EXISTS "Registration";
CREATE TABLE "Registration" ("_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "code" VARCHAR(128), "regdate" VARCHAR(20) DEFAULT NULL, "status" INTEGER DEFAULT (0), "idcategory" INTEGER DEFAULT NULL);
DROP TABLE IF EXISTS "Category";
CREATE TABLE "Category" ("_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" VARCHAR(255));
INSERT INTO "Category" VALUES(1, "BSD: Donnerstag 18:00 - 19:30 Uhr");
INSERT INTO "Category" VALUES(2, "BSD: Dienstag 18:15 - 19:45 Uhr");